# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x08location\"J\n\x0fLocationRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"Y\n\x08Location\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x15\n\rcreation_time\x18\x04 \x01(\t\"9\n\x10LocationResponse\x12%\n\tlocations\x18\x01 \x03(\x0b\x32\x12.location.Location2X\n\x0fLocationService\x12\x45\n\x0cGetLocations\x12\x19.location.LocationRequest\x1a\x1a.location.LocationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONREQUEST']._serialized_start=28
  _globals['_LOCATIONREQUEST']._serialized_end=102
  _globals['_LOCATION']._serialized_start=104
  _globals['_LOCATION']._serialized_end=193
  _globals['_LOCATIONRESPONSE']._serialized_start=195
  _globals['_LOCATIONRESPONSE']._serialized_end=252
  _globals['_LOCATIONSERVICE']._serialized_start=254
  _globals['_LOCATIONSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
