apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: data
          image: deperios/data